In [1]:
import pandas as pd
import numpy as np

print("Hiver Support Agent")
print("Environment is ready!")
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Hiver Support Agent
Environment is ready!
Pandas: 3.0.5
NumPy: 2.5.3

In [2]:
from pathlib import Path
import pandas as pd

sample_path = Path("../data/raw/sample.csv")

df = pd.read_csv(sample_path)

print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Dataset shape: (93, 7)

Columns:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']

In [3]:
pd.set_option("display.max_colwidth", 100)

df.head(10)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,119237,105834,True,Wed Oct 11 06:55:44 +0000 2017,@AppleSupport causing the reply to be disregarded and the tapped notification under the keyboard...,119236,NaN
1,119238,ChaseSupport,False,Wed Oct 11 13:25:49 +0000 2017,"@105835 Your business means a lot to us. Please DM your name, zip code and additional details ab...",NaN,119239.0
2,119239,105835,True,Wed Oct 11 13:00:09 +0000 2017,@76328 I really hope you all change but I'm sure you won't! Because you don't have to!,119238,NaN
3,119240,VirginTrains,False,Tue Oct 10 15:16:08 +0000 2017,@105836 LiveChat is online at the moment - https://t.co/SY94VtU8Kq or contact 03331 031 031 opti...,119241,119242.0
4,119241,105836,True,Tue Oct 10 15:17:21 +0000 2017,@VirginTrains see attached error message. I've tried leaving a voicemail several times in the pa...,119243,119240.0
5,119243,VirginTrains,False,Tue Oct 10 15:25:14 +0000 2017,"@105836 Have you tried from another device, Miriam ^MM",119244,119241.0
6,119244,105836,True,Tue Oct 10 15:26:44 +0000 2017,"@VirginTrains yep, I've tried laptop too several times over the past week and again today. I've ...",119245,119243.0
7,119245,VirginTrains,False,Tue Oct 10 15:33:22 +0000 2017,"@105836 It's working OK from here, Miriam. Does this link help https://t.co/0m2mpH15eh ? ^MM",NaN,119244.0
8,119242,105836,True,Tue Oct 10 15:09:00 +0000 2017,@VirginTrains I still haven't heard &amp; the number I'm directed to by phone is a dead end &amp...,119240,119246.0
9,119246,VirginTrains,False,Tue Oct 10 10:13:19 +0000 2017,@105836 That's what we're here for Miriam 😊 The team should send you an email shortly ^HP,119242,119247.0

In [4]:
df[[
    "tweet_id",
    "author_id",
    "inbound",
    "text",
    "response_tweet_id",
    "in_response_to_tweet_id"
]].head(10)

,tweet_id,author_id,inbound,text,response_tweet_id,in_response_to_tweet_id
0,119237,105834,True,@AppleSupport causing the reply to be disregarded and the tapped notification under the keyboard...,119236,NaN
1,119238,ChaseSupport,False,"@105835 Your business means a lot to us. Please DM your name, zip code and additional details ab...",NaN,119239.0
2,119239,105835,True,@76328 I really hope you all change but I'm sure you won't! Because you don't have to!,119238,NaN
3,119240,VirginTrains,False,@105836 LiveChat is online at the moment - https://t.co/SY94VtU8Kq or contact 03331 031 031 opti...,119241,119242.0
4,119241,105836,True,@VirginTrains see attached error message. I've tried leaving a voicemail several times in the pa...,119243,119240.0
5,119243,VirginTrains,False,"@105836 Have you tried from another device, Miriam ^MM",119244,119241.0
6,119244,105836,True,"@VirginTrains yep, I've tried laptop too several times over the past week and again today. I've ...",119245,119243.0
7,119245,VirginTrains,False,"@105836 It's working OK from here, Miriam. Does this link help https://t.co/0m2mpH15eh ? ^MM",NaN,119244.0
8,119242,105836,True,@VirginTrains I still haven't heard &amp; the number I'm directed to by phone is a dead end &amp...,119240,119246.0
9,119246,VirginTrains,False,@105836 That's what we're here for Miriam 😊 The team should send you an email shortly ^HP,119242,119247.0

In [5]:
df["inbound"].value_counts()

inbound
True     49
False    44
Name: count, dtype: int64

In [6]:
df["inbound"].value_counts(normalize=True) * 100

inbound
True     52.688172
False    47.311828
Name: proportion, dtype: float64

In [7]:
support_messages = df[df["inbound"] == False]

support_messages["author_id"].value_counts().head(20)

author_id
AppleSupport       13
SpotifyCares        8
Tesco               8
VirginTrains        4
British_Airways     3
ChaseSupport        1
O2                  1
comcastcares        1
sprintcare          1
SouthwestAir        1
Ask_Spectrum        1
HPSupport           1
UPSHelp             1
Name: count, dtype: int64

In [8]:
customer_messages = df[df["inbound"] == True]

customer_messages["author_id"].value_counts().head(20)

author_id
105840    4
105847    4
105855    4
105836    3
105848    3
105856    3
105842    2
105844    2
105850    2
105854    2
105857    2
105834    1
105835    1
105837    1
105838    1
105839    1
105841    1
105843    1
82476     1
105845    1
Name: count, dtype: int64

In [9]:
df.isna().sum()

tweet_id                    0
author_id                   0
inbound                     0
created_at                  0
text                        0
response_tweet_id          28
in_response_to_tweet_id    25
dtype: int64

In [10]:
df["created_at"].min(), df["created_at"].max()

('Thu Oct 12 10:25:35 +0000 2017', 'Wed Oct 11 16:28:34 +0000 2017')

In [11]:
print("Unique tweets:", df["tweet_id"].nunique())
print("Unique authors:", df["author_id"].nunique())

Unique tweets: 93
Unique authors: 42

In [12]:
tweet_id = 1

df[
    (df["tweet_id"] == tweet_id) |
    (df["in_response_to_tweet_id"] == tweet_id) |
    (df["response_tweet_id"].astype(str).str.contains(str(tweet_id), na=False))
][[
    "tweet_id",
    "author_id",
    "inbound",
    "text",
    "response_tweet_id",
    "in_response_to_tweet_id"
]]

,tweet_id,author_id,inbound,text,response_tweet_id,in_response_to_tweet_id
0,119237,105834,True,@AppleSupport causing the reply to be disregarded and the tapped notification under the keyboard...,119236,NaN
2,119239,105835,True,@76328 I really hope you all change but I'm sure you won't! Because you don't have to!,119238,NaN
3,119240,VirginTrains,False,@105836 LiveChat is online at the moment - https://t.co/SY94VtU8Kq or contact 03331 031 031 opti...,119241,119242.0
4,119241,105836,True,@VirginTrains see attached error message. I've tried leaving a voicemail several times in the pa...,119243,119240.0
5,119243,VirginTrains,False,"@105836 Have you tried from another device, Miriam ^MM",119244,119241.0
...,...,...,...,...,...,...
86,119328,105858,True,@HPSupport Problem with printhead Serial# TH536D1HN #hpcswus #hpprnt,119327,NaN
88,119330,105859,True,@105860 I wish Amazon had an option of where I can just get it shipped to the ups store so I can...,119329,119331.0
89,119331,105860,True,They reschedule my shit for tomorrow https://t.co/RsvZcT982t,119330,NaN
90,119332,Tesco,False,"@105861 Hey Sara, sorry to hear of the issues you are having, can I ask if it's the lay out or j...",119333,119334.0
91,119333,105861,True,@Tesco bit of both - finding the layout cumbersome and when removing an item from faves - gettin...,"119335,119336",119332.0

In [13]:
df["response_tweet_id"].head(20)

0            119236
1               NaN
2            119238
3            119241
4            119243
5            119244
6            119245
7               NaN
8            119240
9            119242
10              NaN
11           119248
12    119249,119251
13              NaN
14           119252
15           119255
16           119257
17           119258
18           119259
19           119260
Name: response_tweet_id, dtype: str

In [14]:
df["in_response_to_tweet_id"].head(20)

0          NaN
1     119239.0
2          NaN
3     119242.0
4     119240.0
5     119241.0
6     119243.0
7     119244.0
8     119246.0
9     119247.0
10    119249.0
11    119250.0
12         NaN
13    119253.0
14         NaN
15    119256.0
16    119254.0
17    119255.0
18    119257.0
19    119258.0
Name: in_response_to_tweet_id, dtype: float64

In [15]:
df["response_tweet_id"].dtype

In [16]:
df["in_response_to_tweet_id"].dtype

dtype('float64')